; backend/config.example.ini
; Шаблон конфигурации — скопируйте в config.ini и вставьте свои ключи

[yandex]
; API ключ из Yandex Cloud (IAM-токен или API-ключ)
api_key = AQVN2s6J_e8N9jOMtcC_q5ILOlV1v1jujDvflieb

; ID каталога Yandex Cloud (folder_id)
folder_id = b1g5uja1kulv8i3mk8cu


; Название модели (можно не менять)
model = gemma-3-27b-it/latest  
